name: lindo
description: Lindo App

version: 1.0.9+9

environment:
  sdk: ">=2.19.2 <3.0.0"

flutter_localizations:
  sdk: flutter

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  cupertino_icons: ^1.0.5
  connectivity_plus: ^3.0.2
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  animations:
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  expandable_page_view: ^1.0.17
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_database: ^10.0.14
  firebase_analytics:
  firebase_crashlytics:
  firebase_messaging:
  firebase_storage: ^11.2.3
  flutter_local_notifications: ^12.0.4
  intl:
  http:
  pinput:
  carousel_slider: ^4.2.1
  im_stepper: ^1.0.1+1
  flutter_cupertino_datetime_picker: ^3.0.0
  translator:
  uuid:
  story_view: ^0.14.0
  flutter_switch: ^0.3.2
  timeago:
  swipe_stack_null_safe: ^1.0.0
  smooth_page_indicator:
  showcaseview: ^2.0.3
  dismissible_page:
  geolocator: ^9.0.2
  geocoding:
  flutter_overlay_loader: ^2.0.0
  url_launcher: ^6.1.11
  flutter_animate: ^4.1.1+1
  shimmer: ^3.0.0
  emoji_picker_flutter: ^1.6.1
  google_sign_in: ^6.1.4
  video_player: ^2.6.1
  flutter_facebook_auth: ^4.4.1+1 #podfile ios:11
  sign_in_with_apple: ^4.1.0
  in_app_purchase: ^3.1.7
  flutter_countdown_timer: ^4.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio_logger: ^4.0.8+8
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Rubik-Regular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

    - family: Rubik-Medium
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf

    - family: Rubik-Bold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf

    - family: Rubik-Light
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
